- hosts: firewalls
  become: true
  gather_facts: false

  tasks:
    - name: Configure firewall interface (eth0 only)
      shell: |
        ip addr flush dev eth0
        ip addr add 172.20.20.101/24 dev eth0
        ip link set eth0 up

    - name: Enable IP forwarding
      shell: sysctl -w net.ipv4.ip_forward=1

    - name: Allow forwarding (basic policy)
      shell: iptables -P FORWARD ACCEPT

