- hosts: hosts
  become: true
  tasks:
    - name: Configure IP on hosts
      shell: |
        ip addr flush dev eth0
        {% if inventory_hostname == "host1" %}
        ip addr add 172.20.20.110/24 dev eth0
        {% elif inventory_hostname == "host2" %}
        ip addr add 172.20.20.111/24 dev eth0
        {% endif %}
        ip link set eth0 up


